repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=5120"]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -s -w
        language: system
        files: '\.go$'

      - id: goimports
        name: goimports
        entry: goimports -w
        language: system
        files: '\.go$'

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        pass_filenames: false
        files: '\.go$'

      - id: check-filenames
        name: check-filenames
        entry: python ../scripts/check_filenames.py
        language: system
        files: '.*'
